name: Staging|Semantic Release|LPs Front

on:
  push:
    branches:
      - staging
    paths-ignore:
      - '.github/workflows/**'

concurrency:
  group: 'lps-front-staging-release'
  cancel-in-progress: true

jobs:
  semver-release:
    uses: ./.github/workflows/template-semantic-release.yml
    secrets:
      gh_bot_release_id: ${{ secrets.GH_BOT_RELEASE_ID }}
      gh_bot_release_private_key: ${{ secrets.GH_BOT_RELEASE_PRIVATE_KEY }}
